### ISSUE TITLE
Use future_lapply(..., future.seed = TRUE) to get proper random numbers

### ISSUE THREAD

**Issue by HenrikBengtsson** [williazo/tcensReg#3]
Congrats for the CRAN submission.  I see you're using future.apply :+1:   A quick comment about the latter; Don't forget to pass argument `future_lapply(..., future.seed = TRUE)` if you use it with resampling techniques because otherwise, you will not get statistical sound random numbers, e.g. https://github.com/williazo/tcensReg/blob/7ca8904c7d97be14dbcc42c7703871d06a2d4ed9/inst/script/simulation3_noninf.R#L63-L75

**Comment by williazo** [comment]
Thanks @HenrikBengtsson. I will update my usage of the future_lapply function to include these random seeds and read through the documentation more closely as well to prevent errors in the future.

**Comment by williazo** [comment]
All cases of future_lapply have been updated to include random seeds to ensure reproducibility. Thank you.
